### ISSUE TITLE
open tag in a new tab / splitted window

### ISSUE THREAD

**Issue by gnos28** [KosekiDev/vim_config#2]
current shortcut for opening tag is CTRL + ]
opening tab in the same window (closable with CTRL + O)

add another shortcut that doesn't require using altGr key (french keyboard)
this shortcut should open tag in a new tab / splitted window (best choice to be defined)

**Comment by kosekidev** [comment]
You can define your own keymaps in vim 👌
Just edit the keymaps.lua file and add your own or change the plugin's setting.
