### ISSUE TITLE
copy and paste anoying popup

### ISSUE THREAD

**Issue by gnos28** [KosekiDev/vim_config#3]
situation : 2 files opened in splitted windows

yanking code on a pane display a yanked popup info
while this popup is displayed you cant switch to the other pane (CTRL W W put the focus on the popup)
you have to wait until popup disappearing before being able to switch pane & paste your code

**Comment by kosekidev** [comment]
You have the <leader>un keymap to delete all notifications.
But if that kind of messages are really annoying, you can disabled them in the noice plugin. I maybe do so in another update.
